# Task 1 — Iris Flower Classification

**Intern:** Aphile Ashley  
**Track:** Data Science · Oasis Infobyte (OIBSIP)  
**Status:** Section 0–1 written; not yet interpreted

> Sections are added in small groups. Nothing is marked complete until I have
> run it myself and can explain it.

## 0. Setup

- Imports
- Load the dataset with `sklearn.datasets.load_iris(as_frame=True)`
- Build a readable DataFrame with species names

**TODO (after running):** _write what I notice about the loaded data._

In [1]:
# --- Cell 0.1: imports -------------------------------------------------
# pandas   -> tables (DataFrames): rows and columns we can inspect/aggregate
# numpy    -> numbers and arrays (used indirectly by the other libraries)
# load_iris -> ships the real Iris dataset inside scikit-learn (no download)

import numpy as np
import pandas as pd

from sklearn.datasets import load_iris

# Makes any random numbers in this notebook reproducible.
# We will set random_state explicitly on the train/test split later too.
RANDOM_STATE = 42

print("Libraries imported. pandas", pd.__version__)

Libraries imported. pandas 2.3.3

In [2]:
# --- Cell 0.2: load the real dataset -----------------------------------
# as_frame=True returns the data already as a pandas DataFrame (a table)
# instead of raw arrays. The table has our four measurements plus a
# 'target' column that holds the species as numbers 0, 1, 2.

iris = load_iris(as_frame=True)
iris_frame = iris.frame

iris_frame.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [3]:
# --- Cell 0.3: readable DataFrame --------------------------------------
# The 'target' column is 0/1/2, which is hard to read in charts/tables.
# We map those numbers back to the real species names and store them in a
# new column called 'species'. The four measurement columns stay as they are.

df = iris_frame.copy()
df["species"] = pd.Categorical.from_codes(iris.target, iris.target_names)

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa

## 1. Data inspection

- Shape
- Data types
- Null values
- Descriptive statistics
- Species counts

**TODO (my observation):** _write what I notice about the dataset._

In [4]:
# --- Cell 1.1: shape and data types ------------------------------------
# .shape gives (rows, columns). .dtypes tells us what kind of value each
# column holds (float64 = decimal numbers, category = a fixed set of labels).

print("Shape (rows, columns):", df.shape)
print()
print("Data types:")
print(df.dtypes)

Shape (rows, columns): (150, 6)

Data types:
sepal length (cm)     float64
sepal width (cm)      float64
petal length (cm)     float64
petal width (cm)      float64
target                  int64
species              category
dtype: object

In [5]:
# --- Cell 1.2: missing values ------------------------------------------
# isnull() marks every empty cell; .sum() counts them per column.
# If every count is 0, there is nothing to clean before modelling.

print("Null counts per column:")
print(df.isnull().sum())
print()
print("Total nulls:", int(df.isnull().sum().sum()))

Null counts per column:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
species              0
dtype: int64

Total nulls: 0

In [6]:
# --- Cell 1.3: descriptive statistics ----------------------------------
# describe() summarises each numeric column: count, mean, std (spread),
# min, 25%/50%/75% quartiles and max. species is excluded because it is
# a label, not a number.

df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [7]:
# --- Cell 1.4: species counts ------------------------------------------
# value_counts() shows how many rows belong to each species.
# A balanced dataset (equal counts) means accuracy will be a fair metric.

print("Rows per species:")
print(df["species"].value_counts())
print()
print("Proportions:")
print(df["species"].value_counts(normalize=True).round(3))

Rows per species:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

Proportions:
species
setosa        0.333
versicolor    0.333
virginica     0.333
Name: proportion, dtype: float64

## 2. Exploratory visualisation

- Pair plot / scatter matrix coloured by species
- Box plots for each feature

**TODO (my observation):** _which measurements appear most discriminative,
and what in the charts shows that._

_Not yet added — waiting for my review of Sections 0–1._

## 3. Train/test split

- Reproducible ~80/20 split with `stratify=y` and a fixed `random_state`

**TODO (explain in my own words):** _what stratification changed about the
class distribution in train vs test._

## 4. Model training

- At least two classifiers (e.g. Logistic Regression, KNN / Decision Tree)
- Scaling inside a `Pipeline`, fit on training data only

**TODO:** _why scaling is needed for some of these models and not others._

## 5. Evaluation on the same held-out test set

- Accuracy
- Confusion matrix
- Precision, recall, F1 / classification report

**TODO (my interpretation):** _read every number in the classification
reports and say what it means for this problem._

## 6. Model selection

**TODO (my decision):** _which model I select based on the actual test
results above, and why — written only after seeing the numbers._

## 7. Conclusions and reflections

- **TODO:** key findings in my own words
- **TODO:** limitations of this analysis
- **TODO:** what I learned and what I would improve

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
species              0
dtype: int64
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64
/home/wethinkcode/Desktop/Personal_Projects/OIBSIP/.venv/bin/python